### ISSUE TITLE
Unique Incident

### ISSUE THREAD

**Issue by JacobWren** [jacobkap/nibrsbook#8]
Hello Dr. Kaplan,

Within the administrative segment, the ORI-incident number combination uniquely identifies each crime incident. This “uniqueness” property is only true for a particular year. Now, there is a “year” variable and an “incident date” variable. The year associated with the “incident date” variable is not necessarily the same as the “year” variable. So, does this “uniqueness” property of the ORI-incident number combination hinge on the "year” variable or within the year associated with the “incident date” variable? And does the “exceptional clearance date” variable have any effect on this year distinction?

Thanks

**Comment by jacobkap** [comment]
Yes it is supposed to be unique within a single agency in a single year. It should be based on the year variable since there can (rarely) be incidents with a date other than the current year. Which I believe are either reporting crimes that occurred before the agency started using NIBRS or are errors. The exceptional clearance date doesn't affect the year distinction.

**Comment by JacobWren** [comment]
@jacobkap Okay so you're saying that when some agencies start using NIBRS, rather than just reporting to NIBRS thereafter, they go back in time and submit x years of past incidents?
